version: '3.3'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_DATABASE: wordpress
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - ./dev.php.ini:/usr/local/etc/php/php.ini
      - ./wp-content:/var/www/html/wp-content

volumes:
  wordpress:
  db: